name: iottree-edge
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy
  - opencv
  - flask
  - flask-cors
  - pip
  - pytorch
  - torchvision
  - cpuonly  # 如果用GPU，请删除此行，并使用CUDA选项
  - pip:
    - ultralytics
    - pillow
    - av
    - mediapipe
    - opencv-python
